export HISTSIZE=50000
export SAVEHIST=50000
ZSH_THEME="robbyrussell"

function commit () {
  git add -A
  git commit -m "$1"
  git push
}

# get current directory
BASEDIR=$(dirname "$0")

# check system name
systemName=$(uname -n)
if [ $systemName = "Cartan" ]; then
    source $BASEDIR/cartan
elif [ $systemName = "Green.local" ]; then
   source $BASEDIR/green
elif [ $systemName = "bahamankolibri.lin.tuni.fi" ]; then
   source $BASEDIR/bahamankolibri
else
fi

export PATH="$LOC_PATH:$PATH"

if [ $systemName = "bahamankolibri.lin.tuni.fi" ]; then
  alias cdr="cd $LOC_HOME/repository"
else
  alias cdr="cd $LOC_HOME/repo"
fi


ZSH_AUTOSUGGEST_STRATEGY=(history completion)
source $BASEDIR/zsh-autosuggestions/zsh-autosuggestions.zsh

source $BASEDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

echo "Welcome to $systemName"

plugins=(git fzf history)

alias ls='ls --color=auto'
alias l='ls -la'
alias ..="cd .."
alias pull="git pull"
alias c="cmake -S . -B build -G Ninja"
alias b="cmake --build build"
alias te="emacsclient -nw"
